# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170718_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
