# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
